version: '3'
services:
  redis:
    image: 'registry.cn-hangzhou.aliyuncs.com/openyourdream/redis:7.4.0'
    restart: unless-stopped
    privileged: true
    # 添加密码为Admin-667788
    environment:
      REDIS_PASSWORD: Admin-667788
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - '/data/docker-volumes/redis:/data'
    ports:
      - '16379:6379'
    # network_mode: host
    container_name: redis
