version: '3'
services:
  zookeeper:
    image: 'registry.cn-hangzhou.aliyuncs.com/openyourdream/zookeeper:3.9.2'
    restart: unless-stopped
    privileged: true
    volumes:
      - "/etc/localtime:/etc/localtime"
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    tty: true
    container_name: zookeeper
  kafka:
    image: 'registry.cn-hangzhou.aliyuncs.com/openyourdream/kafka:3.8.0'
    restart: unless-stopped
    privileged: true
    volumes:
      - "/etc/localtime:/etc/localtime"
    ports:
      - '9092:9092'
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: 192.168.8.203:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.8.203:9092
    tty: true
    depends_on:
      - zookeeper
    container_name: kafka
  kafka-manager:
    image: 'registry.cn-hangzhou.aliyuncs.com/openyourdream/kafka-manager:1.3.1.8'                        
    restart: unless-stopped  
    environment:                     
      ZK_HOSTS: 192.168.8.203:2181
      APPLICATION_SECRET: hao
      KAFKA_MANAGER_AUTH_ENABLED: true
      KAFKA_MANAGER_USERNAME: admin  
      KAFKA_MANAGER_PASSWORD: Admin-667788
    ports:                            
      - "9000:9000"
    depends_on:                         
      - kafka
    container_name: kafka-manager